// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ4YtcPakXNF2jOgsgYowHyJCWYzYqqZU',
    appId: '1:764100098173:web:4492c66eeb91d8c59cd914',
    messagingSenderId: '764100098173',
    projectId: 'classimed-dfe31',
    authDomain: 'classimed-dfe31.firebaseapp.com',
    storageBucket: 'classimed-dfe31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoX5HFPkrG7oP-cRy4LT7fDZw4poIJFUY',
    appId: '1:764100098173:android:c1929e502edda6489cd914',
    messagingSenderId: '764100098173',
    projectId: 'classimed-dfe31',
    storageBucket: 'classimed-dfe31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjHqUVO9exs7BKAwdSv7cBpj-1zFYqUPA',
    appId: '1:982900658398:ios:402384a4a75a24b2ad324f',
    messagingSenderId: '982900658398',
    projectId: 'chatflutter-1f705',
    storageBucket: 'chatflutter-1f705.firebasestorage.app',
    androidClientId: '982900658398-t91ab14riih4m9212ao69n3p8npfmrc3.apps.googleusercontent.com',
    iosClientId: '982900658398-e39oeleshqkedhrljnaplb54sh43n3f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.classiMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjHqUVO9exs7BKAwdSv7cBpj-1zFYqUPA',
    appId: '1:982900658398:ios:402384a4a75a24b2ad324f',
    messagingSenderId: '982900658398',
    projectId: 'chatflutter-1f705',
    storageBucket: 'chatflutter-1f705.firebasestorage.app',
    androidClientId: '982900658398-t91ab14riih4m9212ao69n3p8npfmrc3.apps.googleusercontent.com',
    iosClientId: '982900658398-e39oeleshqkedhrljnaplb54sh43n3f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.classiMed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ4YtcPakXNF2jOgsgYowHyJCWYzYqqZU',
    appId: '1:764100098173:web:eb7748ab860904129cd914',
    messagingSenderId: '764100098173',
    projectId: 'classimed-dfe31',
    authDomain: 'classimed-dfe31.firebaseapp.com',
    storageBucket: 'classimed-dfe31.firebasestorage.app',
  );

}